/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OTO;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class OtoView extends javax.swing.JFrame {

    /**
     * Creates new form OtoView
     * 
     */ ArrayList<Oto> mau = new ArrayList<>();
     DefaultTableModel defaultTableModel;
     QLOTO ql = new QLOTO();
    public OtoView() {
        initComponents();
           mau.add(new Oto("01", "Roll","Vang", "Moi"));
            mau.add(new Oto("02", "TOyota","Den", "Cu"));
         mau.add(new Oto("03", "MINI","Do", "Moi"));
         mau.add(new Oto("03", "MINI","Nau", "Moi"));
         mau.add(new Oto("03", "MINI","Cam", "Moi"));
        for (Oto oto : mau) {
            cboMau.addItem(oto.getMau());
        }
       ArrayList<Oto> list = ql.getlist();
        loadData(list);
    }
  void loadData(   ArrayList<Oto> list ){
  defaultTableModel = (DefaultTableModel) tblOTO.getModel();
  defaultTableModel.setRowCount(0);
      for (Oto oto : list) {
          defaultTableModel.addRow(new Object[]{
          oto.getMa(),oto.getTen(),oto.getMau(),oto.getTrangthai()
          });
      }
  }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboMau = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        rdMoi = new javax.swing.JCheckBox();
        rdCu = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOTO = new javax.swing.JTable();
        btoADD = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btoXua = new javax.swing.JButton();
        btoTim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("OTO");

        jLabel2.setText("Mã");

        jLabel3.setText("Tên Xe");

        jLabel4.setText("Màu");

        jLabel5.setText("Trạng Thái");

        buttonGroup1.add(rdMoi);
        rdMoi.setText("Mới");

        buttonGroup1.add(rdCu);
        rdCu.setText("Cũ");

        tblOTO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ", "Tên", "Màu", "Trạng Thái"
            }
        ));
        tblOTO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOTOMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOTO);

        btoADD.setText("ADD");
        btoADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btoADDMouseClicked(evt);
            }
        });

        jButton2.setText("Xoa");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        btoXua.setText("Sửa");
        btoXua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btoXuaMouseClicked(evt);
            }
        });

        btoTim.setText("Tim");
        btoTim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btoTimMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(140, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btoTim))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cboMau, 0, 117, Short.MAX_VALUE)
                                                    .addComponent(txtTen)
                                                    .addComponent(txtMa))
                                                .addGap(71, 71, 71))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(rdMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(rdCu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btoADD, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(btoXua))))
                        .addGap(100, 100, 100))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btoADD))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btoXua)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdMoi)
                    .addComponent(rdCu)
                    .addComponent(btoTim))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblOTOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOTOMouseClicked
        // TODO add your handling code here:
        int row = tblOTO.getSelectedRow();
        String ma = (String) tblOTO.getValueAt(row, 0);
        txtMa.setText(ma);
        String ten = (String) tblOTO.getValueAt(row, 1);
        txtTen.setText(ten);
        String mau = (String) tblOTO.getValueAt(row, 2);
        cboMau.setSelectedItem(mau);
          String trangthai = (String) tblOTO.getValueAt(row, 3);
          if (trangthai.equals("Moi")) {
            rdMoi.setSelected(true);
        }else{
          
          rdCu.setSelected(true);
          }
    }//GEN-LAST:event_tblOTOMouseClicked

    private void btoADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btoADDMouseClicked
        // TODO add your handling code here:
        String ma = txtMa.getText();
        String ten = txtTen.getText();
        String mau = (String) cboMau.getSelectedItem();
        String  trangthai = "";
        if (rdCu.isSelected()) {
            trangthai="Moi";
        }else{
         trangthai="Cu";
        }
        Oto oto =new Oto(ma, ten, mau, trangthai);
        Boolean addnew = ql.addNew(oto);
        if (addnew) {
            JOptionPane.showMessageDialog(this, "Them ThanH Cong");
            loadData(ql.getlist());
        }
    }//GEN-LAST:event_btoADDMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        int row = tblOTO.getSelectedRow();
        Boolean delete = ql.delete(row);
        if (delete) {
            JOptionPane.showMessageDialog(this, "Xoa Thanh cong");
            loadData(ql.getlist());
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void btoXuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btoXuaMouseClicked
        // TODO add your handling code here:
        int row = tblOTO.getSelectedRow();
          String ma = txtMa.getText();
        String ten = txtTen.getText();
        String mau = (String) cboMau.getSelectedItem();
        String  trangthai = "";
        if (rdCu.isSelected()) {
            trangthai="Moi";
        }else{
         trangthai="Cu";
        }
          Oto oto =new Oto(ma, ten, mau, trangthai);
        Boolean update = ql.update(row, oto);
        if (update) {
            JOptionPane.showMessageDialog(this, "Xua Thanh cong");
            loadData(ql.getlist());
        }
    }//GEN-LAST:event_btoXuaMouseClicked

    private void btoTimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btoTimMouseClicked
        // TODO add your handling code here:
        String ten = txtMa.getText();
        ArrayList<Oto> tim = ql.tim(ten);
        loadData(tim);
    }//GEN-LAST:event_btoTimMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OtoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btoADD;
    private javax.swing.JButton btoTim;
    private javax.swing.JButton btoXua;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboMau;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox rdCu;
    private javax.swing.JCheckBox rdMoi;
    private javax.swing.JTable tblOTO;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
