/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NhanVien;

import Swing.SV;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class SinhVienView extends javax.swing.JFrame {

    /**
     * Creates new form SinhVienView
     */
    ArrayList<SV> list = new ArrayList<>();
    QuanLyNhanVien ql = new QuanLyNhanVien();
    DefaultTableModel defaultTableModel;
    ArrayList<NhanVien> nhanvien = new ArrayList<>();
    public SinhVienView() {
        initComponents();
        list.add(new SV("Ho Vu Chien", 9));
        list.add(new SV("Ho Nam", 9));
        list.add(new SV("Ho Cuong", 9));
        list.add(new SV("Ho Vu Manh", 9));
        for (SV sv : list) {
            cboSinhVien.addItem(sv.getTen());
        }
          nhanvien.add(new NhanVien("Nv1","Chien","Nam","SD"));
          nhanvien.add(new NhanVien("Nv2","Chien","Nam","1"));
          nhanvien.add(new NhanVien("Nv3","Chien","Nam","SD"));
          for (NhanVien nhanVien : nhanvien) {
            cboLop.addItem(nhanVien.getLop());
        }
          
        ArrayList<NhanVien> list = ql.getlist();
        LoadDaTa(list);

    }

    void LoadDaTa(ArrayList<NhanVien> list) {
        defaultTableModel = (DefaultTableModel) tblNhanVien.getModel();
        defaultTableModel.setRowCount(0);
        for (NhanVien nhanVien : list) {
            defaultTableModel.addRow(new Object[]{
                nhanVien.getMaNV(),
                nhanVien.getHoTen(),
                nhanVien.getGioiTinh(),
                nhanVien.getLop()
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        cboSinhVien = new javax.swing.JComboBox<>();
        btoChon = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        rdNam = new javax.swing.JCheckBox();
        rdNu = new javax.swing.JCheckBox();
        cboLop = new javax.swing.JComboBox<>();
        btoThem = new javax.swing.JButton();
        btoXoa = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnGhiFile = new javax.swing.JButton();
        btnDocFile = new javax.swing.JButton();

        jButton3.setText("SUA");

        jButton2.setText("XOA");

        jButton1.setText("ADD");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btoChon.setText("Chọn");
        btoChon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btoChonMouseClicked(evt);
            }
        });

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã SV", "Họ Tên", "Giới tính", "Lớp"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        jLabel1.setText("Họ Tên");

        jLabel2.setText("Mã SV");

        buttonGroup1.add(rdNam);
        rdNam.setText("Nam");

        buttonGroup1.add(rdNu);
        rdNu.setText("Nữ");

        btoThem.setText("Thêm");
        btoThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btoThemMouseClicked(evt);
            }
        });

        btoXoa.setText("Xoa");
        btoXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btoXoaMouseClicked(evt);
            }
        });
        btoXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoXoaActionPerformed(evt);
            }
        });

        jButton4.setText("Xua");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        btnGhiFile.setText("Ghi Vào File");
        btnGhiFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGhiFileMouseClicked(evt);
            }
        });

        btnDocFile.setText("Đọc FIlE");
        btnDocFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDocFileMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btoChon))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(cboLop, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnGhiFile))
                                .addGap(85, 85, 85)
                                .addComponent(btnDocFile)))))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtHoTen))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btoXoa)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(rdNam, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdNu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(cboSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btoThem)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btoChon)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btoXoa))
                        .addGap(31, 31, 31)
                        .addComponent(cboSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btoThem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdNam)
                    .addComponent(rdNu))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGhiFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDocFile)
                        .addGap(32, 32, 32)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btoChonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btoChonMouseClicked
        // TODO add your handling code here:
        String name = (String) cboSinhVien.getSelectedItem();
        for (SV sv : list) {
            if (sv.getTen().equals(name)) {
                JOptionPane.showMessageDialog(this, sv.toString());
            }

        }


    }//GEN-LAST:event_btoChonMouseClicked

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        //Lấy dòng vừa chọn
        int row = tblNhanVien.getSelectedRow();
       String ma = (String) tblNhanVien.getValueAt(row, 0);
       txtMa.setText(ma);
        String ten = (String) tblNhanVien.getValueAt(row, 1);
        txtHoTen.setText(ten);
        String lop = (String) tblNhanVien.getValueAt(row, 3);
        cboLop.setSelectedItem(lop);
        String gioitinh = (String) tblNhanVien.getValueAt(row, 2);
        if (gioitinh.equals("Nam")) {
            rdNam.setSelected(true);
        }else{
        rdNu.setSelected(true);
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btoThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btoThemMouseClicked
        // TODO add your handling code here:
        //Lấy Giá trị trên from
        String ma = txtMa.getText();
        String ten = txtHoTen.getText();
        String lop = (String) cboLop.getSelectedItem();
        String gioitinh ="";
        if (rdNam.isSelected()) {
            gioitinh="Nam";
        }else{
        gioitinh ="Nữ";
        }
        //Tạo đtuong từ các thông tin trên  
         if (ma.isEmpty()|| ten.isEmpty()) {
                 JOptionPane.showMessageDialog(this, "ma kh dc bo trong");
             }else{
        NhanVien nhanvien = new NhanVien(ma,ten,gioitinh,lop);      
        //Thêm  nhan Vien Vao list
        Boolean chackAdd = ql.addNew(nhanvien);  
        if (chackAdd) {   
            JOptionPane.showMessageDialog(this, "them Tahnh cong");  
            LoadDaTa(ql.getlist());
            }
   
         }
    }//GEN-LAST:event_btoThemMouseClicked

    private void btoXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btoXoaMouseClicked
        // TODO add your handling code here:
        int row = tblNhanVien.getSelectedRow();
        Boolean check = ql.delete(row);
        if (check) {
            JOptionPane.showMessageDialog(this,"xoa Ok" );
            LoadDaTa(ql.getlist());
        }
    }//GEN-LAST:event_btoXoaMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        int row = tblNhanVien.getSelectedRow();
         String ma = txtMa.getText();
        String ten = txtHoTen.getText();
        String lop = (String) cboLop.getSelectedItem();
        String gioitinh ="";
        if (rdNam.isSelected()) {
            gioitinh="Nam";
        }else{
        gioitinh ="Nữ";
        }
        //Tạo đtuong từ các thông tin trên  
        NhanVien nhanvien = new NhanVien(ma,ten,gioitinh,lop);
        
        //Thêm  nhan Vien Vao list
        Boolean chackupdate = ql.update(row, nhanvien);
        if (chackupdate) {
            JOptionPane.showMessageDialog(this, "Xua Tahnh cong");
            LoadDaTa(ql.getlist());
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void btoXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btoXoaActionPerformed
 public void GhiFile() throws IOException{
   File file = new File("data.txt");
        if (!file.exists()) {
           file.createNewFile();
            return ;
        }
        FileOutputStream fos = new FileOutputStream(file);
        ObjectOutputStream oos = new ObjectOutputStream(fos);
        ArrayList<NhanVien> list = ql.getlist();
        for (NhanVien nhanVien : list) {
         oos.writeObject(nhanVien);
     }
        fos.close();
        oos.close();
 }
    private void btnGhiFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGhiFileMouseClicked
        try {
            // TODO add your handling code here:
            GhiFile();
        } catch (IOException ex) {
            Logger.getLogger(SinhVienView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnGhiFileMouseClicked
public void docFile() throws FileNotFoundException, IOException, ClassNotFoundException{
  File file = new File("data.txt");
        if (!file.exists()) {//Kiểm tra sự tồn tại của file
            System.out.println("File này không tìm thấy");
            return;
        }
 //Mo FILE
    FileInputStream fis = new FileInputStream(file);
    //Doc tung dong
     ObjectInputStream ois = new ObjectInputStream(fis);
     ArrayList<NhanVien>  list =new ArrayList<>();
     while(fis.available()>0){
     list.add((NhanVien) ois.readObject());
     }
     ois.close();
        fis.close();
        LoadDaTa(list);
}
    
    private void btnDocFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocFileMouseClicked
        try {
            // TODO add your handling code here:
            docFile();
        } catch (IOException ex) {
            Logger.getLogger(SinhVienView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SinhVienView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDocFileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinhVienView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocFile;
    private javax.swing.JButton btnGhiFile;
    private javax.swing.JButton btoChon;
    private javax.swing.JButton btoThem;
    private javax.swing.JButton btoXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboLop;
    private javax.swing.JComboBox<String> cboSinhVien;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox rdNam;
    private javax.swing.JCheckBox rdNu;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMa;
    // End of variables declaration//GEN-END:variables
}
